export const ALGER_COMMUNES = [
  'Aïn Bénian',
  'Aïn Taya',
  'Algiers Centre (Alger Centre)',
  'Baba Hassen',
  'Bab El Oued',
  'Bab Ezzouar',
  'Bachedjerah',
  'Baraki',
  'Ben Aknoun',
  'Beni Messous',
  'Birkhadem',
  'Bir Mourad Raïs',
  'Birtouta',
  'Bologhine',
  'Bordj El Bahri',
  'Bordj El Kiffan',
  'Bourouba',
  'Bouzaréah',
  'Casbah',
  'Chéraga',
  'Dar El Beïda',
  'Dely Ibrahim',
  'Djesser Kasentina',
  'Draria',
  'Douera',
  'El Achour',
  'El Biar',
  'El Hammamet',
  'El Harrach',
  'El Madania',
  'El Magharia',
  'El Marsa',
  'El Mouradia',
  "H'raoua",
  'Hussein Dey',
  'Hydra',
  'Khraicia',
  'Kouba',
  'Mahelma',
  'Mohammedia',
  'Oued Koriche',
  'Oued Smar',
  'Ouled Chebel',
  'Ouled Fayet',
  'Rahmania',
  'Raïs Hamidou',
  'Reghaïa',
  'Rouïba',
  'Sidi M\'Hamed',
  'Sidi Moussa',
  'Souidania',
  'Staoueli',
  'Tessala El Merdja',
  'Zéralda'
] as const;

export type AlgerCommune = typeof ALGER_COMMUNES[number];
