import { Profile, ServiceListing, ServiceRequest, Review } from '@/types';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'usr_admin_1',
    role: 'admin',
    full_name: 'Sarah Connor (Site Coordinator)',
    phone: '+1 (555) 019-2831',
    location: 'Central Downtown',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    bio: 'Platform Owner & Offline Coordinator. Managing safe bookings and verification.',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr_provider_1',
    role: 'provider',
    full_name: 'Elena Rostova',
    phone: '+1 (555) 432-8765',
    location: 'Westside & Suburban Area',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    bio: 'Certified early childhood educator with 7+ years of experience in infant and toddler care. CPR & First Aid certified.',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr_provider_2',
    role: 'provider',
    full_name: 'David Chen, M.Sc.',
    phone: '+1 (555) 876-1234',
    location: 'North Hill / University District',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Mathematics & Physics tutor for middle/high school and university prep. 5 years tutoring experience.',
    created_at: '2026-01-12T11:30:00Z',
  },
  {
    id: 'usr_provider_3',
    role: 'provider',
    full_name: 'Claire Beauchamp',
    phone: '+1 (555) 345-6789',
    location: 'East Park & Riverside',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Nanny and creative babysitter. Loves engaging children in montessori-inspired arts, crafts, and reading.',
    created_at: '2026-01-15T09:15:00Z',
  },
  {
    id: 'usr_provider_4',
    role: 'provider',
    full_name: 'Marcus Vance',
    phone: '+1 (555) 789-0123',
    location: 'South Metro & Downtown',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'Bilingual English/Spanish teacher specializing in conversational practice, homework support, and SAT prep.',
    created_at: '2026-01-18T14:20:00Z',
  },
  {
    id: 'usr_client_1',
    role: 'client',
    full_name: 'Jessica Miller',
    phone: '+1 (555) 234-5678',
    location: 'Westside',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bio: 'Parent of two (ages 3 and 6). Seeking weekend babysitters and reading tutors.',
    created_at: '2026-02-01T12:00:00Z',
  },
];

export const INITIAL_LISTINGS: ServiceListing[] = [
  {
    id: 'lst_1',
    provider_id: 'usr_provider_1',
    category: 'babysitting',
    title: 'Experienced & Caring Infant & Toddler Babysitter',
    description: 'Hello parents! I offer gentle, attentive, and reliable childcare for infants and toddlers. I hold current pediatric CPR and First Aid certifications, and bring age-appropriate sensory games and bedtime storybooks. Fully comfortable with meal prep and nighttime routines.',
    price: 24,
    availability: 'Weekdays 4:00 PM – 10:00 PM, Weekends Full Day',
    location: 'Westside & Suburban Area',
    photo_url: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-01-11T12:00:00Z',
  },
  {
    id: 'lst_2',
    provider_id: 'usr_provider_2',
    category: 'teaching',
    title: 'High School & College Math & Physics Tutoring',
    description: 'Personalized 1-on-1 tutoring in Algebra, Geometry, Calculus, and AP Physics. I focus on building core intuitive understanding, eliminating test anxiety, and developing strong problem-solving habits. In-person sessions with homework review and tailored practice sets.',
    price: 45,
    availability: 'Mon, Wed, Fri 3:00 PM – 8:00 PM, Sat Morning',
    location: 'North Hill / University District',
    photo_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-01-13T15:00:00Z',
  },
  {
    id: 'lst_3',
    provider_id: 'usr_provider_3',
    category: 'babysitting',
    title: 'Creative Montessori-Inspired Babysitter (Ages 2-10)',
    description: 'Looking for someone who will engage your kids without screens? I bring arts & crafts, outdoor play, and educational games. 4+ years of babysitting experience with multiple glowing family references.',
    price: 22,
    availability: 'Tuesday & Thursday afternoons, Saturday evenings',
    location: 'East Park & Riverside',
    photo_url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-01-16T10:00:00Z',
  },
  {
    id: 'lst_4',
    provider_id: 'usr_provider_4',
    category: 'teaching',
    title: 'French & Spanish Language Tutoring (All Levels)',
    description: 'Native French speaker & fluent Spanish instructor. Whether you need academic reinforcement for school or conversational practice for travel, my interactive immersion sessions will boost confidence rapidly.',
    price: 38,
    availability: 'Flexible weekday evenings & Sunday afternoons',
    location: 'South Metro & Downtown',
    photo_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-01-19T16:45:00Z',
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 'req_1',
    client_id: 'usr_client_1',
    listing_id: 'lst_1',
    requested_datetime: '2026-09-20T18:00:00Z',
    note: 'Need babysitting for 2 children (3 and 6 years old) for our anniversary dinner. We have a friendly golden retriever.',
    status: 'completed',
    created_at: '2026-09-10T14:30:00Z',
  },
  {
    id: 'req_2',
    client_id: 'usr_client_1',
    listing_id: 'lst_2',
    requested_datetime: '2026-09-22T16:00:00Z',
    note: 'Initial calculus diagnostic session for high school senior preparing for upcoming midterm exam.',
    status: 'in_progress',
    created_at: '2026-09-14T09:15:00Z',
  },
  {
    id: 'req_3',
    client_id: 'usr_client_1',
    listing_id: 'lst_3',
    requested_datetime: '2026-09-25T14:00:00Z',
    note: 'Saturday afternoon craft workshop and babysitting for 4-year-old daughter.',
    status: 'new',
    created_at: '2026-09-15T18:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    request_id: 'req_1',
    rating: 5,
    comment: 'Elena was absolutely fantastic! On time, incredibly calm and patient with both kids, and sent regular peace-of-mind text updates during the evening. We will definitely book through this platform again.',
    created_at: '2026-09-21T09:00:00Z',
  },
];
